app:
     resource: @AppBundle/Controller/
     prefix:   /{_locale}/
     defaults: { _locale: en }

app_homepage:
     path: /{_locale}
     methods: [GET, POST]
     defaults: { _controller: AppBundle:Default:index, _locale: en}