services:

    acme_locale.locale_listener:
            class: AppBundle\EventListener\LocaleListener
            arguments: ["%kernel.default_locale%"]
            tags:
                - { name: kernel.event_subscriber }

    requesthandler:
            class:     AppBundle\Services\MailerHandler
            arguments: ["@mailer"]

    requesthandler:
            class:     AppBundle\Services\RequestHandler
            arguments: ["@request_stack"]
